# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DolphinAi < Formula
  desc "dolphin-ai is an AI agent platform with multi-agent coordination,
MCP tool integration, skills, cron tasks, and multi-provider LLM support.
"
  homepage "https://github.com/dolphinZzv/dolphin"
  version "0.2.8"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.8/dolphin-ai_0.2.8_macOS_x86_64.tar.gz"
      sha256 "e559fcc7d100fe1bb308bd8dd91795714eecf868acabed1c64860f1da4e1b827"

      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.8/dolphin-ai_0.2.8_macOS_arm64.tar.gz"
      sha256 "f6e758622518796830a8e5a15c7126915496618e0ddb885ca23bbe0f2006b0d3"

      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.8/dolphin-ai_0.2.8_linux_x86_64.tar.gz"
      sha256 "7db0c40d904d15931e83f92dd13ceaa7db4831a8412bada667276bd965756c58"
      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.8/dolphin-ai_0.2.8_linux_arm64.tar.gz"
      sha256 "dc7098079364d902a845bf0549b90c4b96f9b7ce035aacd06cea4d222d916b21"
      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
  end

  def caveats
    <<~EOS
      dolphin-ai is installed. Run `dolphin-ai setup` to get started.

      For CDP browser automation, install chromium or google-chrome.
      See https://github.com/dolphinZzv/dolphin for documentation.
    EOS
  end
end
