# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DolphinAi < Formula
  desc "dolphin-ai is an AI agent platform with multi-agent coordination,
MCP tool integration, skills, cron tasks, and multi-provider LLM support.
"
  homepage "https://github.com/dolphinZzv/dolphin"
  version "0.2.9"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.9/dolphin-ai_0.2.9_macOS_x86_64.tar.gz"
      sha256 "1d2248ceeef4f654840db30fbde3c75bbb492ff79c55b96a6f302978b4adbbd1"

      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.9/dolphin-ai_0.2.9_macOS_arm64.tar.gz"
      sha256 "30a444c10ccd6d1c083e1ff67a7ebbd33313f7596c0809dd2dbd2c9d91aeca3b"

      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.9/dolphin-ai_0.2.9_linux_x86_64.tar.gz"
      sha256 "a2a7fd03111fc46e0fa3a0ce3643a6a4c05c5cf0505f23aed983d593df9c0fbc"
      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.9/dolphin-ai_0.2.9_linux_arm64.tar.gz"
      sha256 "ebc4520d95d1fb63ac90da3e9442503914432095b724b6d91a65170429f0c464"
      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
  end

  def caveats
    <<~EOS
      dolphin-ai is installed. Run `dolphin-ai setup` to get started.

      For CDP browser automation, install chromium or google-chrome.
      See https://github.com/dolphinZzv/dolphin for documentation.
    EOS
  end
end
