# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dolphin < Formula
  desc "dolphin is an AI agent platform with multi-agent coordination,
MCP tool integration, skills, cron tasks, and multi-provider LLM support.
"
  homepage "https://github.com/dolphinZzv/dolphin"
  version "0.1.7"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.1.7/dolphin_0.1.7_macOS_x86_64.tar.gz"
      sha256 "c5ee3dc0d41f18cbc51ae2d506b3666bf5e74e3dc9ba2d75a6be318149475c53"

      define_method(:install) do
        bin.install "dolphin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.1.7/dolphin_0.1.7_macOS_arm64.tar.gz"
      sha256 "5766bf3d5537f268d8b8c7ef6b01b6fbe2ade0124ad6ac8b8d3d14c3507e6f01"

      define_method(:install) do
        bin.install "dolphin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.1.7/dolphin_0.1.7_linux_x86_64.tar.gz"
      sha256 "c1ae0eb8650386035a0890612a0c6b62b8fb9bd884444163cb87bb8ed072397e"
      define_method(:install) do
        bin.install "dolphin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.1.7/dolphin_0.1.7_linux_arm64.tar.gz"
      sha256 "051fcb9308fd5fcf4da6f91fc9b1ded919d9b89c393867123c32d70332df5b1e"
      define_method(:install) do
        bin.install "dolphin"
      end
    end
  end

  def caveats
    <<~EOS
      dolphin is installed. Run `dolphin setup` to get started.

      For CDP browser automation, install chromium or google-chrome.
      See https://github.com/dolphinZzv/dolphin for documentation.
    EOS
  end
end
