# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DolphinAi < Formula
  desc "dolphin-ai is an AI agent platform with multi-agent coordination,
MCP tool integration, skills, cron tasks, and multi-provider LLM support.
"
  homepage "https://github.com/dolphinZzv/dolphin"
  version "0.2.1"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.1/dolphin-ai_0.2.1_macOS_x86_64.tar.gz"
      sha256 "12c94d9946297f086f24fda1a252f01ae73c1c7c297f220755ce07ca7c07b6b1"

      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.1/dolphin-ai_0.2.1_macOS_arm64.tar.gz"
      sha256 "dfffa5d656366cd5448b8e5ae748e5a346a151083b28c501b878a2cd5fe99763"

      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.1/dolphin-ai_0.2.1_linux_x86_64.tar.gz"
      sha256 "c7683a1b0c5c6778b924580280ab44cbd68b50a818c9d9f461913f41fa87576d"
      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dolphinZzv/dolphin/releases/download/v0.2.1/dolphin-ai_0.2.1_linux_arm64.tar.gz"
      sha256 "0abd68c5bc065d1fb229e26dc26414812ef5cb4f764e1bac72fafee5bffa64e2"
      define_method(:install) do
        bin.install "dolphin-ai"
      end
    end
  end

  def caveats
    <<~EOS
      dolphin-ai is installed. Run `dolphin-ai setup` to get started.

      For CDP browser automation, install chromium or google-chrome.
      See https://github.com/dolphinZzv/dolphin for documentation.
    EOS
  end
end